name: Build and Deploy to EC2

on:
  push:
    branches:
      - main   # runs only when PRs are merged into main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests   # builds JAR in target/

      - name: Upload JAR to EC2 (/tmp/target)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/tmp/"   # 👈 matches your deploy.sh

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Make sure the script is executable
            chmod +x ~/deploy.sh
            # Execute the deploy script WITH SUDO
            sudo ~/deploy.sh
